// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StubbedContext;

#nullable disable

namespace StubbedContext.Migrations
{
    [DbContext(typeof(StubbedContext))]
    partial class StubbedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Entities.AlbumEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 1L,
                            Name = "Album 1",
                            Visibility = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 2L,
                            Name = "Album 2",
                            Visibility = 2
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 3L,
                            Name = "Album 3",
                            Visibility = 1
                        });
                });

            modelBuilder.Entity("Entities.ContainsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomTitle")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contains");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AlbumId = 1L,
                            CustomTitle = "Custom Title 1",
                            TrackId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AlbumId = 1L,
                            CustomTitle = "Custom Title 2",
                            TrackId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            AlbumId = 2L,
                            CustomTitle = "Custom Title 3",
                            TrackId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            AlbumId = 2L,
                            CustomTitle = "Custom Title 4",
                            TrackId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            AlbumId = 3L,
                            CustomTitle = "Custom Title 5",
                            TrackId = 5L
                        });
                });

            modelBuilder.Entity("Entities.FriendEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FriendId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FriendId = 3L,
                            Strength = 0,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            FriendId = 2L,
                            Strength = 0,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("Entities.TrackEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Artist = "Artist 1",
                            Duration = 180L,
                            Rating = 4.5,
                            Title = "Track 1"
                        },
                        new
                        {
                            Id = 2L,
                            Artist = "Artist 2",
                            Duration = 200L,
                            Rating = 4.0,
                            Title = "Track 2"
                        },
                        new
                        {
                            Id = 3L,
                            Artist = "Artist 3",
                            Duration = 240L,
                            Rating = 5.0,
                            Title = "Track 3"
                        },
                        new
                        {
                            Id = 4L,
                            Artist = "Artist 4",
                            Duration = 210L,
                            Rating = 3.5,
                            Title = "Track 4"
                        },
                        new
                        {
                            Id = 5L,
                            Artist = "Artist 5",
                            Duration = 190L,
                            Rating = 4.2000000000000002,
                            Title = "Track 5"
                        });
                });

            modelBuilder.Entity("Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Role = 2,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Role = 1,
                            Username = "User1"
                        },
                        new
                        {
                            Id = 3L,
                            Role = 1,
                            Username = "User2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
